### ISSUE TITLE
Fix errors on login page when logging in with wrong credentials

### ISSUE THREAD

**Issue by twanh** [twanh/note-system-server#5]

**Comment by twanh** [comment]
```
server_1    | 172.18.0.1 - - [21/Aug/2021 13:06:34] "POST /auth/login/api/ HTTP/1.1" 200 -
server_1    | 172.18.0.1 - - [21/Aug/2021 13:06:52] "POST /auth/login/api/ HTTP/1.1" 200 -
server_1    | 172.18.0.1 - - [21/Aug/2021 13:06:58] "POST /auth/login/api/ HTTP/1.1" 200 -
server_1    | 172.18.0.1 - - [21/Aug/2021 13:25:04] "POST /auth/login/api/ HTTP/1.1" 500 -
server_1    | Traceback (most recent call last):
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
server_1    |     return self.wsgi_app(environ, start_response)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
server_1    |     response = self.handle_exception(e)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
server_1    |     response = self.full_dispatch_request()
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
server_1    |     rv = self.handle_user_exception(e)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
server_1    |     rv = self.dispatch_request()
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
server_1    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
server_1    |   File "/server/server/auth/routes.py", line 99, in api_login
server_1    |     if user.check_password(password):
server_1    | AttributeError: 'NoneType' object has no attribute 'check_password'
server_1    | 172.18.0.1 - - [21/Aug/2021 13:42:30] "POST /auth/login/api/ HTTP/1.1" 500 -
server_1    | Traceback (most recent call last):
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
server_1    |     return self.wsgi_app(environ, start_response)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
server_1    |     response = self.handle_exception(e)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
server_1    |     response = self.full_dispatch_request()
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
server_1    |     rv = self.handle_user_exception(e)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
server_1    |     rv = self.dispatch_request()
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
server_1    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
server_1    |   File "/server/server/auth/routes.py", line 99, in api_login
server_1    |     if user.check_password(password):
server_1    | AttributeError: 'NoneType' object has no attribute 'check_password'
server_1    | 172.18.0.1 - - [21/Aug/2021 13:43:25] "POST /auth/login/api/ HTTP/1.1" 500 -
server_1    | Traceback (most recent call last):
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
server_1    |     return self.wsgi_app(environ, start_response)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
server_1    |     response = self.handle_exception(e)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
server_1    |     response = self.full_dispatch_request()
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
server_1    |     rv = self.handle_user_exception(e)
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
server_1    |     rv = self.dispatch_request()
server_1    |   File "/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
server_1    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
server_1    |   File "/server/server/auth/routes.py", line 99, in api_login
server_1    |     if user.check_password(password):
server_1    | AttributeError: 'NoneType' object has no attribute 'check_password'

```
